CV/urls.py
#! /usr/bin/env python
# -*- encoding: UTF-8 -*-
from django.urls import path

from . import views

urlpatterns = [
    path('<str:username>', views.CvView.as_view(), name='cv'),
    path('', views.CvList.as_view(), name='cv_list'),
]

Perso/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('CV/', include('CV.urls')),
    path('', views.HomeView.as_view(), name='home'),
]

CV/models.py
from datetime import date

from django.contrib.auth.models import User
from django.db import models
from django.forms import ValidationError


class SkillCategory(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Skill categories"

    def __str__(self):
        return self.name


class Cv(models.Model):
    AVAILABILITY_TYPE_NOW = "NOW"
    AVAILABILITY_TYPE_OFFSET = "OFFSET"
    AVAILABILITY_TYPE_AT = "AT"
    AVAILABILITY_TYPE = (
        (AVAILABILITY_TYPE_NOW, 'now'),
        (AVAILABILITY_TYPE_OFFSET, 'offset'),
        (AVAILABILITY_TYPE_AT, 'at'),
    )

    AVAILABILITY_OFFSET_MONTH = "MONTH"
    AVAILABILITY_OFFSET_DAY = "DAY"
    
    AVAILABILITY_OFFSET = (
        (AVAILABILITY_OFFSET_DAY, 'day'),
        (AVAILABILITY_OFFSET_MONTH, 'month'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    begin = models.DateField(null=True, blank=True)  # to compute experience

    availability_type = models.CharField(max_length=64, choices=AVAILABILITY_TYPE, default=AVAILABILITY_TYPE_NOW)
    availability_date = models.DateField(null=True, blank=True, help_text="if 'Availability type' is 'at'")
    availability_offset_number = models.IntegerField(null=True, blank=True, help_text="if 'Availability type' is 'offset'")
    availability_offset_quantity = models.CharField(max_length=64, choices=AVAILABILITY_OFFSET, default=AVAILABILITY_OFFSET_MONTH, help_text="if 'Availability type' is 'offset'")
    

    @classmethod
    def is_availability_valide(cls, availability_type, availability_date, availability_offset_number, availability_offset_quantity):
        if availability_type == cls.AVAILABILITY_TYPE_OFFSET:
            if not availability_offset_number or not availability_offset_quantity:
                return "availability offset expected"

        if availability_type == cls.AVAILABILITY_TYPE_AT:
            if not availability_date:
                return "availability date expected"
        return None

    def get_experience(self):
        delta = date.today() - self.begin
        return int(delta.days/365.25)

    def get_skills(self):
        skills = self.skill_set.all()
        ordered_skills = {}
        for skill in skills:
            if skill.category.name in ordered_skills:
                ordered_skills[skill.category.name].append(skill.name)
            else:
                ordered_skills[skill.category.name] = [skill.name]
        return ordered_skills

    def __str__(self):
        return self.user.username

    def clean(self):
        error = self.is_availability_valide(self.availability_type, self.availability_date, self.availability_offset_number, self.availability_offset_quantity)
        if error:
            raise ValidationError(error)


class Skill(models.Model):
    category = models.ForeignKey(SkillCategory, on_delete=models.CASCADE)
    owner = models.ForeignKey(Cv, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    order = models.IntegerField()

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.name + " (" + self.category.name + ")"


class Formation(models.Model):
    cv = models.ForeignKey(Cv, on_delete=models.CASCADE)
    content = models.CharField(max_length=1024)
    order = models.IntegerField()

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.content


class Company(models.Model):
    cv = models.ForeignKey(Cv, on_delete=models.CASCADE)
    name = models.CharField(max_length=1024)
    website_link = models.CharField(max_length=512, blank=True)
    begin = models.DateField()
    end = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "companies"

    def __str__(self):
        return self.name


class Experience(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    title = models.CharField(max_length=1024)
    duration = models.CharField(max_length=255)
    begin = models.DateField()
    end = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['-begin', ]

    def __str__(self):
        return self.title


class MissionFunction(models.Model):
    experience = models.ForeignKey(Experience, on_delete=models.CASCADE)
    content = models.CharField(max_length=1024)
    order = models.IntegerField()

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.content


class MissionTechnical(models.Model):
    experience = models.ForeignKey(Experience, on_delete=models.CASCADE)
    content = models.CharField(max_length=1024)
    order = models.IntegerField()

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.content

CV/views.py
# Create your views here.
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.views import generic
from django.views.generic import ListView

from .models import Cv, Formation, Company


class CvList(ListView):
    model = Cv
    context_object_name = "cv_list"


class CvView(generic.TemplateView):
    template_name = "CV/cv.html"

    def get_context_data(self, username):
        user = get_object_or_404(User, username=username)

        cv = get_object_or_404(Cv, user=user)
        formations = Formation.objects.filter(cv=cv).all()
        companies = Company.objects.filter(cv=cv).order_by('-begin').all()

        context = {
            "user": {'full_name': user.get_full_name()},
            "cv": cv,
            "formations": formations,
            "companies": companies,
        }
        return context

Home/views.py
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = "Home/home.html"

Perso/views.py
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = "index.html"

CV/templates/CV/cv.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>{{ user.full_name }}</title>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'CV/style.css' %}" />
</head>
<body>
<section id="introduction">
    <h1>{{ user.full_name }}</h1>
    <p class="banner">{{ cv.title }}</p>
    <div id="introduction-details">
        <p>{{ cv.get_experience }} ans d'expérience</p>
        <div class="vsep"/>
        {% if cv.availability_type == "NOW" %}
        <p>Disponible immédiatement</p>
        {% elif cv.availability_type == "OFFSET" %}
            {% with cv.availability_offset_number as number %}
            {% if cv.availability_offset_quantity == "MONTH" %}
            <p>Disponible sous {{ number }} mois</p>
            {% elif cv.availability_offset_quantity == "DAY" %}
            <p>Disponible sous {{ number }} jour{{number|pluralize:",s"}}</p>
            {% elif debug %}
            <script type="text/javascript">
                alert("wrong availability_offset_quantity " + "{{cv.availability_offset_quantity}}");
            </script>
            {% endif %}
            {% endwith %}
        {% elif cv.availability_type == "AT" %}
        <p>Disponible le {{ cv.availability_date }}</p>
        {% elif debug %}
        <script type="text/javascript">
            alert("wrong availability_type " + "{{cv.availability_type}}");
        </script>
        {% endif %}
    </div>
</section>
<section id="competences">
    <h2>Mes compétences</h2>
    <div id="competence_list">
        {% for category, skill_list in cv.get_skills.items %}
        <div class="competence_element">
            <div class="competence_content">
                <h3>{{ category }}</h3>
                <ul>
                    {% for skill in skill_list %}
                    <li>{{ skill }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endfor %}
    </div>
</section>
<section id="formation">
    <h2>Ma formation</h2>
    <ul>
        {% for formation in formations %}
        <li>{{ formation.content|safe }}</li>
        {% endfor %}
    </ul>
</section>
<section id="experiences">
    <h2>Mon expérience</h2>
    <div class="company">
        {% for company in companies %}
        {% if company.website_link %}
        <h3><a href="{{company.website_link}}">{{ company.name }}</a></h3>
        {% else %}
        <h3>{{ company.name }}</h3>
        {% endif %}
        {% if company.end %}
        <p class="date">Du {{ company.begin }} au {{ company.end }}</p>
        {% else %}
        <p class="date">Depuis le {{ company.begin }}</p>
        {% endif %}
        <div class="experience_list">
            {% for experience in company.experience_set.all %}
            <div class="experience">
                <h4>{{ experience.title|safe }}</h4>
                <p>Durée : {{ experience.duration }}</p>
                <h5>Projet et missions</h5>
                <ul>
                    {% for function in experience.missionfunction_set.all %}
                    <li>{{ function.content }}</li>
                    {% endfor %}
                </ul>
                <h5>Environnement technique</h5>
                <ul>
                    {% for function in experience.missiontechnical_set.all %}
                    <li>{{ function.content }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</section>
<section id="footer"/>
</body>
</html>

CV/templates/CV/cv_list.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>CV</title>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'CV/style.css' %}" />
</head>
<body>
    {% for cv in cv_list %}
        <li><a href="{{cv.user.username}}">{{cv.user.get_full_name }} - {{ cv.title }}</a></li>
    {% endfor %}
</body>
</html>

Perso/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mon site perso</title>
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
</head>
<body>
<h1>Contenu du site</h1>
<a href="{% url 'cv_list' %}">Voir les CV</a>
<h1>Mes profiles</h1>
<ul>
<li><a href="https://github.com/bdribault">Github</a></li>
<li><a href="https://www.codingame.com/profile/264d3729399d7e4707d039999f21d1281687711">Codingame</a></li>
<li><a href="https://trailhead.salesforce.com/fr/me/bdribault">Trailhead Salesforce</a></li>
<li><a href="https://twitter.com/BDribault">Twitter</a></li>
<li><a href="www.linkedin.com/in/bdribault">LinkedIn</a></li>
</ul>
</body>
</html>